// AUTO-GENERATED by tools/wagon-bg/horizon_detect.py — do not hand-edit.
// Maps each backdrop painting filename to the y-coordinate (in painting
// pixels) of its horizon line. BackdropPainting uses this to align the
// painting's horizon with the scene's HORIZON_Y, regardless of where
// the painting itself happens to place the horizon.

export const BACKDROP_HORIZONS: Record<string, number> = {
  'backdrop-desert-2.webp': 310,
  'backdrop-desert-3.webp': 102,
  'backdrop-desert.webp': 612,
  'backdrop-forest-1.webp': 543,
  'backdrop-forest-2.webp': 663,
  'backdrop-forest-3.webp': 683,
  'backdrop-forest-4.webp': 598,
  'backdrop-forest.webp': 571,
  'backdrop-mountains-1.webp': 689,
  'backdrop-mountains-3.webp': 78,
  'backdrop-mountains.webp': 86,
  'backdrop-prairie-1.webp': 487,
  'backdrop-prairie-2.webp': 545,
  'backdrop-prairie-3.webp': 548,
  'backdrop-prairie-4.webp': 491,
  'backdrop-prairie.webp': 551,
};
