"""Detect the horizon line Y in a backdrop painting.

Sky is blue-dominant; ground is green/yellow-dominant. We compute mean
B-G per row and find the row with the most-negative gradient — that's
the sky→ground transition. Restricting to the middle 90% of the image
avoids edge artifacts from sampler/VAE.

Usage:
    python horizon_detect.py            # scan static/wagon-bg/, emit TS
    python horizon_detect.py file.webp  # one-off, print result
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from PIL import Image

THIS_DIR = Path(__file__).parent
STATIC_DIR = THIS_DIR.parent.parent / "static" / "wagon-bg"
TS_OUT = (
    THIS_DIR.parent.parent / "src" / "lib" / "ui" / "wagon" / "terrain"
    / "backdrop-horizons.ts"
)

# Painterly transitions span 30-50 rows, so we look at the difference
# between bands above and below each candidate row rather than per-row
# gradients (which are noisy on painterly textures).
SMOOTH_WIN = 40
# Minimum (B-G_above - B-G_below) for a row to count as "horizon-like".
# Sky is blue-shifted; ground is green/yellow-shifted. Below this the
# image probably has no clear sky→ground transition.
MIN_DROP = 6


def detect_horizon_y(path: Path) -> int | None:
    """Return horizon-y in pixels from top of the painting, or None when
    the image has no clear sky→ground transition."""
    img = np.array(Image.open(path).convert("RGB"))
    height = img.shape[0]
    mean = img.mean(axis=1)
    bg = mean[:, 2].astype(int) - mean[:, 1].astype(int)

    # For each row, compare the average B-G of the SMOOTH_WIN rows above
    # vs SMOOTH_WIN rows below. Horizon = where (above - below) is
    # maximized, i.e. sky is most-blue above and most-green below.
    edge = SMOOTH_WIN + int(height * 0.05)
    above = np.array([bg[y - SMOOTH_WIN : y].mean() for y in range(edge, height - edge)])
    below = np.array([bg[y : y + SMOOTH_WIN].mean() for y in range(edge, height - edge)])
    drop = above - below
    idx = int(np.argmax(drop))
    if drop[idx] < MIN_DROP:
        return None
    return idx + edge


def emit_ts() -> None:
    """Scan STATIC_DIR for backdrop-*.webp files and write a TS map."""
    files = sorted(p for p in STATIC_DIR.glob("backdrop-*.webp") if "--" not in p.name)
    entries: dict[str, int] = {}
    for path in files:
        h = detect_horizon_y(path)
        if h is None:
            print(f"  WARN: {path.name} — no clear horizon, will use painting center")
            continue
        entries[path.name] = h
        print(f"  {path.name:<40s} horizon-y = {h:3d} ({100*h/768:5.1f}%)")

    lines = [
        "// AUTO-GENERATED by tools/wagon-bg/horizon_detect.py — do not hand-edit.",
        "// Maps each backdrop painting filename to the y-coordinate (in painting",
        "// pixels) of its horizon line. BackdropPainting uses this to align the",
        "// painting's horizon with the scene's HORIZON_Y, regardless of where",
        "// the painting itself happens to place the horizon.",
        "",
        "export const BACKDROP_HORIZONS: Record<string, number> = {",
    ]
    for name, h in entries.items():
        lines.append(f"  {name!r}: {h},")
    lines.append("};")
    lines.append("")
    TS_OUT.write_text("\n".join(lines))
    print(f"\nwrote {len(entries)} entries to {TS_OUT.relative_to(THIS_DIR.parent.parent)}")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        path = Path(sys.argv[1])
        h = detect_horizon_y(path)
        if h is None:
            print("no clear horizon detected")
        else:
            print(f"horizon-y = {h} ({100*h/768:.1f}% from top)")
    else:
        emit_ts()
