"""Generate WAGON BODY ONLY raster sprites (no wheels, no oxen, no driver).

Hybrid+ pipeline: each wagon component generated separately as a FLUX
raster sprite, then composited via SVG layers with individual animation.
This script is the wagon body — bed + canvas + tongue + jockey toolbox.

Wheels, oxen, driver, butter pail, tar bucket, chicken coop, water kegs
are separate FLUX sprites generated by their own scripts.

Outputs at static/wagon-bg/wagon-body/<wagon-model>--<condition>.png.
Per wagon model × per condition stop (5 stops: fresh / dusty / worn /
ragged / failing).
"""

from pathlib import Path

from flux_client import generate_to, ping

OUT_DIR = Path(__file__).parent.parent.parent / "static" / "wagon-bg" / "wagon-body"

WIDTH = 1536
HEIGHT = 640


# Strong language to exclude wheels + animals + driver. FLUX often
# wants to render the full scene — explicit framing as a "structural
# bed shell" floating in space helps.
COMMON_FRAMING = (
    "Painterly oil painting in the style of Albert Bierstadt and Hudson "
    "River School. The wagon body floats alone in the frame against a "
    "plain cream-white background, with NO WHEELS visible, NO "
    "UNDERCARRIAGE, NO AXLES — only the wagon BED and CANVAS BONNET "
    "and TONGUE are shown. The space below the bed where wheels would "
    "be is EMPTY. NO oxen, NO mules, NO horses, NO animals of any kind. "
    "NO driver, NO people, NO figures. NO landscape, NO ground, NO "
    "scene. Brush stroke detail period 1840s."
)


VARIANTS = [
    (
        "prairie-schooner--fresh",
        810001,
        "Side view of a 1840s emigrant prairie schooner wagon BODY ONLY: "
        "the wood-plank bed extending nearly to where the axles would be, "
        "weathered brown unpainted oak with visible vertical plank grain "
        "and iron banding at the corners. The off-white double-thickness "
        "cotton duck canvas BONNET stretched TIGHT over six visible "
        "hickory bow ribs running across the top, with the foremost and "
        "rearmost bows framing CINCHED CIRCULAR DRAWSTRING OPENINGS at "
        "front and rear (you can see the dark interior through them). "
        "Wood TONGUE extending forward from the front of the bed. Iron-"
        "banded jockey toolbox at the front of the bed. Driver bench "
        "seat plank on top of the toolbox. Clean fresh-out-of-Independence "
        "appearance, period 1840s. The wagon faces LEFT in the frame. "
        + COMMON_FRAMING,
    ),
    (
        "light--fresh",
        820002,
        "Sharp detailed side view of a 1840s small emigrant LIGHT FARM "
        "WAGON BODY: shorter wood-plank bed than a prairie schooner, "
        "weathered brown unpainted oak with sharp visible vertical plank "
        "grain and clean iron banding details. Smaller off-white cotton "
        "duck canvas BONNET stretched tight over four hickory bow ribs, "
        "with crisp cinched drawstring openings at front and rear, dark "
        "interior visible through the cinched holes. Short wood tongue "
        "extending forward. Small driver bench seat at the front of the "
        "bed. Clean fresh-out-of-the-outfitter appearance, period 1840s, "
        "high detail, sharp focus, brush stroke detail. Wagon faces LEFT. "
        + COMMON_FRAMING,
    ),
    (
        "heavy--fresh",
        830001,
        "Side view of a 1840s heavy CONESTOGA-style FREIGHT WAGON BODY "
        "ONLY: a long wood-plank bed with the distinctive boat-shaped "
        "curve where the bed front and rear ends curve UPWARD (the "
        "Conestoga signature). Weathered dark brown wood with elaborate "
        "iron banding wrapping the curved sides and hand-forged hardware "
        "details. Large off-white double-thickness cotton duck canvas "
        "BONNET stretched tight over seven hickory bow ribs that follow "
        "the upturned bed shape, creating a SAILING-SHIP silhouette "
        "with cinched drawstring openings at front and rear. Single "
        "wood TONGUE extending forward from the front. Period 1840s. "
        "Wagon faces LEFT. "
        + COMMON_FRAMING,
    ),
]


def main() -> None:
    import sys
    if not ping():
        raise SystemExit("ComfyUI not reachable at http://127.0.0.1:8188")
    filter_names = set(sys.argv[1:])
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    selection = [v for v in VARIANTS if not filter_names or v[0] in filter_names]
    print(f"FLUX-generating {len(selection)} wagon-body variant(s)\n")
    for i, (name, seed, prompt) in enumerate(selection, 1):
        out = OUT_DIR / f"{name}.png"
        print(f"[{i}/{len(selection)}] {out.name}  ({WIDTH}x{HEIGHT}, seed={seed})", flush=True)
        generate_to(out, prompt, WIDTH, HEIGHT, seed)
        print(f"   -> {out.relative_to(Path(__file__).parent.parent.parent)}\n")
    print("done.")


if __name__ == "__main__":
    main()
